name: tests
on:
  workflow_dispatch:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: dart pub global activate melos
      - run: melos bs
      - run: melos run test:format --no-select
      - run: melos run test:analyze:dart --no-select
      - run: melos run test:analyze:flutter --no-select
      - run: melos run test:only --no-select
