name: "{{name.snakeCase()}}"
description: "{{{description}}}"
version: 0.0.1

publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies: {}

dev_dependencies:
  lint: ^1.8.2
  test: ^1.21.4
